### ISSUE TITLE
Publickey Cache

### ISSUE THREAD

**Issue by ungenannter** [JonathanCoe/bitseal#5]
I seems the client is requesting the public key for an address every time a message is sent. So when i send 3 Messages to one address, the client is requesting the public key 3 times.

**Comment by JonathanCoe** [comment]
Thanks for reporting the issue Marc. When you say it seems that the client is requesting the public key every time a message is sent, are you getting this from the UI or from watching the log output?

When you send a message, the first message status is always 'Retrieving encryption keys' but that does not necessarily indicate that a server request is being made.

**Comment by ungenannter** [comment]
Hey, i don't have any logs. I did some more testing: the key is cached as expected - i was wrong. But the UI is telling me that a PoW is done after "recieving" the cached pubkey ?

**Comment by JonathanCoe** [comment]
Yes, it sounds like this is just a case of the UI being confusing. When Bitseal sends a message, the first thing it does is try to retrieve the destination pubkey, either from disk or from a server if necessary. Signing, encryption, and POW are all done after that.

I'll change the message status texts so that 'Retrieving encryption keys' is only shown when Bitseal has to request the pubkey from a server. Hopefully that will make things clearer.

**Comment by JonathanCoe** [comment]
This is fixed in commit ed53dd3.
